### ISSUE TITLE
no sound within PlaydateSimulator

### ISSUE THREAD

**Issue by jonknapp** [headblockhead/nix-playdatesdk#1]
I am having issues getting sound to play through `PlaydateSimulator` and am not sure where to look to try and fix the issue. I'm on a non-nixOS machine (linux / PopOS).

I was wondering if either 1) sound doesn't work so far in the simulator, or if 2) it does work but on a different setup (ex: nixOS)

Thanks a lot for putting this out there, it's allowing me to play around with creating my own take on providing the playdate sdk through nix, possibly as a home-manager module since the simulator seems pretty rigid on what it allows for configuration locations.

**Comment by headblockhead** [comment]
Hello! Glad to know my work is appreciated, I am using NixOS and have working sound in PlayDate Simulator. 

I am not very familiar with PopOS myself, so as a staring point, could you send the output of 'pacmd list-clients' while 
PlaydateSimulator is running? 

This command should list the apps connected to PulseAudio. "ALSA plug-in [pds]" is what you need to look for.

Also, could you please send what you are you using/doing to run PlaydateSimulator? (list of commands, nix config, etc.) 

It would be most helpful if you could!

**Comment by jonknapp** [comment]
`pacmd list-clients` outputs `No PulseAudio daemon running, or not running as session daemon.`

PopOS uses PipeWire instead of a PulseAudio server (https://support.system76.com/articles/audio/) so I started to try messing with that instead. Oddly, I'm now getting seemingly random sound from the simulator. It seems to work if I start the simulator immediately after rebooting.

When it did stop playing sounds, I got it to work by running `sudo alsa force-reload`, but again, not sure if that's the solution for my setup or not without trying it more when it breaks. I _think_ I can get it to break more often if I start without a `~/.Playdate Simulator/` ini file already in place pointing to a writable Playdate SDK folder.

Thanks a lot for thinking about it and helping me debug. Currently assuming that something is getting hung up between the PopOS and the dev shell, but if I can reload `alsa` on my end and get it working then I'm going to close this out. Here's what I'm working with so far:

`flake.nix`
```
{
  description = "A collection of tools to help with developing for Panic's Playdate.";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      PlaydateSimulator = { runScript ? "PlaydateSimulator" }: import ./playdate-sdk.nix {
        inherit pkgs runScript;
        stdenv = pkgs.stdenv;
        fetchurl = pkgs.fetchurl;
      };
    in
    {
      defaultPackage.x86_64-linux = PlaydateSimulator { };
      devShells.x86_64-linux.default = (PlaydateSimulator { runScript = "bash"; }).env;
    };
}
```

`playdate-sdk.nix`
```
{ stdenv
, fetchurl
, pkgs
, runScript ? "PlaydateSimulator"
}:
let
  version = "1.13.2";
  PlaydateSimulator = stdenv.mkDerivation rec {
    inherit version;

    name = "playdate-sdk";
    src = fetchurl {
      url = "https://download.panic.com/playdate_sdk/Linux/PlaydateSDK-${version}.tar.gz";
      sha256 = "oJYksh51FxmWa27B4+qT05DmgC1vpK+PGTXscoDPI1M=";
    };
    buildInputs = [ pkgs.webkitgtk ];
    nativeBuildInputs = [ pkgs.autoPatchelfHook pkgs.gnome3.adwaita-icon-theme pkgs.libcanberra pkgs.wrapGAppsHook ];
    installPhase = ''
      runHook preInstall

      root=$out/opt/playdate-sdk-${version}

      # sdk source
      mkdir -p $root
      cp -r ./ $root
      ln -s $root $out/opt/playdate-sdk

      # binaries
      mkdir -p $out/bin
      cp $root/bin/PlaydateSimulator $out/bin/PlaydateSimulator
      cp $root/bin/gamecontrollerdb.txt $out/bin/gamecontrollerdb.txt

      runHook postInstall
    '';
  };
in
pkgs.buildFHSUserEnv {
  inherit runScript;
  name = "PlaydateSimulator";
  targetPkgs = pkgs: [ pkgs.alsa-lib PlaydateSimulator ];
}
```

which I can then run the simulator with `nix develop` followed by `PlaydateSimulator` _or_ I can run `nix build` and then `./result/bin/PlaydateSimulator`.
