### ISSUE TITLE
Bump version to 2.0.3

### ISSUE THREAD

**Issue by kintrix007** [headblockhead/nix-playdatesdk#2]
The current newest Playdate SDK version is 2.0.3, it would be great if you could update this flake to fetch that version instead. I am sadly not familiar with flakes, but I could still *try* making a PR.

**Comment by headblockhead** [comment]
Hello! I have just pushed 28bd15fa82ab21b4ad22f1050d57fbaf36b9e6fc. Thanks for making me aware of the new version, and thanks for using my tool!

If you can, please test this on your machine.
Use `--refresh` to force nix to look for my new commit. You may have to reconfigure PlayDate Simulator to use the new sdk folder (in your $HOME), and make sure to copy your settings over from the old sdk if you want to keep them.

**Comment by headblockhead** [comment]
@kintrix007 I have updated the flake to the latest version. I will close this issue now. If you have any problems, feel free to reopen with details.

**Comment by kintrix007** [comment]
> Hello! I have just pushed [28bd15f](https://github.com/headblockhead/nix-playdatesdk/commit/28bd15fa82ab21b4ad22f1050d57fbaf36b9e6fc). Thanks for making me aware of the new version, and thanks for using my tool!
> 
> If you can, please test this on your machine. Use `--refresh` to force nix to look for my new commit. You may have to reconfigure PlayDate Simulator to use the new sdk folder (in your $HOME), and make sure to copy your settings over from the old sdk if you want to keep them.

Thank you so much for making this tool. It works flawlessly. I did need to select the SDK path again, but that was simple enough.
Everything seems to work flawlessly so far, although I haven't tested much. You have saved me so much trouble by making this!
